name: Dev to server

on: 
  push:
    branches: 
      - main

jobs:
  deploy_node:
    runs-on: self-hosted
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        
    steps:
      - name: Test SSH Connection
        run: |
          sshpass -p "${{ secrets.DEV_PASS }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }} \
          "echo Connected && pwd && ls -la"
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Test Git access
        run: |
          ssh -T git@github.com || true
        

      - name: Clone and install dependencies
        run: |
          cd /var/www/backend && git clone https://github.com/saikat373/nodeupload.git .
      - name: Check Out Git
        uses: actions/checkout@v4
        
      - name: Reconnect with SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run node modules
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install
        run: |
          cd /var/www/backend && npm install
      - name: Install MYSQL
        uses: actions/checkout@v4
      - name: MYSQL LINUX
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -u root -proot -e "SELECT 1"; do
            echo "Waiting..."
            sleep 5
          done
      - name: Check DB
        run: mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"

