name: Dev to server

on: 
  push:
    branches: 
      - main

jobs:
  deploy_node:
    runs-on: self-hosted

    steps:
      - name: Test SSH Connection
        run: |
          sshpass -p "${{ secrets.DEV_PASS }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }} \
          "echo Connected && pwd && ls -la"

      - name: Install nginx
        run: |
          sudo apt update
          sudo apt install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Deploy via rsync
        run: |
          sshpass -p "${{ secrets.DEV_PASS }}" rsync -rz \
          --no-perms --no-owner --no-group --omit-dir-times \
          --exclude='.git' \
          --exclude='__MACOSX' \
          --exclude='**/.DS_Store' \
          ./ ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }}:/var/www/nodeapp

