name: Dev to server

on: 
  push:
    branches: 
      - main

jobs:
  deploy_node:
    runs-on: self-hosted

    steps:
      - name: Test SSH Connection
        run: |
          sshpass -p "${{ secrets.DEV_PASS }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }} \
          "echo Connected && pwd && ls -la"
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Test Git access
        run: |
          ssh -T git@github.com || true
      - name: Make directory
        run: |
          sudo cd /var/www && mkdir backend
          sudo chown -R sishu:sishu backend
        
      - name: Clone repository
        run: |
            cd /var/www/backend && git clone https://github.com/saikat373/nodeupload.git .
            node install

      

